name: Test macOs 26 build

on:
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  do-build-tests-arm-26:
    runs-on: macos-26
    steps:
      - name: Prepare
        run: |
          brew update
          # I've been (intermittently) getting this error:
          # Error: cmake is already installed from local/pinned!
          # Please `brew uninstall cmake` first."
          # so lets try that
          brew uninstall cmake

      - name: Build
        run: |
          echo "Tapping..."
          brew tap bepaald/signalbackup-tools https://github.com/bepaald/signalbackup-tools
          echo "Installing..."
          brew install --HEAD --verbose signalbackup-tools
          echo "Testing..."
          brew test signalbackup-tools
          echo "done!"

      - name: Post
        run: |
          find /Library/Developer/CommandLineTools/ -name cstring
          tail -n 20 ~/Library/Logs/Homebrew/signalbackup-tools/02.cmake.log
