name: Test Windows Build

on:
 workflow_dispatch:
   branches:
     - main

jobs:
  do-build-tests-cmake:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          vcpkg install sqlite3:x64-windows
          
      - name: Build cmake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DWIN32_GITHUB_RUNNER=1 -Dunofficial-sqlite3_DIR="C:/vcpkg/packages/sqlite3_x64-windows/share/unofficial-sqlite3/"
          cmake --build build/ -j 8
