name: Test Linux build

#on: push

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  do-build-tests:
    runs on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends -V g++ libsqlite3-dev libssl-dev

      - name: Build default
        run: |
          g++ --std=c++2a */*.cc *.cc -o signalbackup-tools -lcrypto -lsqlite3

#      - name: Clean 1
#        run: |
#          rm signalbackup-tools
#
#      - name: Build simple script
#        run: |
#          sh BUILDSCRIPT.sh
#
#      - name: Clean 2
#        run: |
#          rm */o/*.o
#          rm o/*.o
#          rm signalbackup-tools
#
#      - name: Build new script
#         run: |
#         bash BUILDSCRIPT_MULTIPROC.bash44
#
#      - name: Clean 3
#        run: |
#          rm */o/*.o
#          rm o/*.o
#          rm signalbackup-tools
